### ISSUE TITLE
allow forceUpdate on `POST` requests

### ISSUE THREAD

**Issue by peters313** [kuitos/axios-extensions#46]
would it be possible to allow a forceUpdate (or clear the cache for that matter) to happen on a Post/Put/Delete request? that way if you do simply just local state updates when adding/updating/deleting on the ui but if the component were to mount again, it would see that the cache is no longer there and make the API request to generate a new cache

**Comment by kuitos** [comment]
duplicated with https://github.com/kuitos/axios-extensions/issues/2

**Comment by AndrewCraswell** [comment]
@kuitos This is not a duplicate of #2. What I believe @peters313 is saying, is that certain methods against and endpoint should remove an existing GET from the cache.

For example, if I hit the endpoint like so:
GET /api/profile/ [Real request]
POST /api/profile/ [Should remove the Get from the cache since the object has likely changed]
GET /api/profile/ [Real request]
GET /api/profile/ [Pulls from cache]

This could get more advanced by checking the Status code response, but at the very least, PUT, POST, and DELETE methods are expected to modify the resource, so we should throw away any cached GET.

**Comment by AndrewCraswell** [comment]
For reference, seems that `axios-cache-adapter` operates like this by default as described [here](https://github.com/RasCarlito/axios-cache-adapter#invalidate-cache-entries).

**Comment by kuitos** [comment]
sorry for my misunderstand, I think u could control your cache by yourself, as not every project follow the rest api spec, related issue https://github.com/kuitos/axios-extensions/issues/52
