### ISSUE TITLE
{cache:false} does not make a new request

### ISSUE THREAD

**Issue by Hyperblaster** [kuitos/axios-extensions#71]
As per the documentation, adding {cache:false} should make a request, however it does not.
axios: 0.19.2
axios-extensions 3.1.2

```js

import {
    cacheAdapterEnhancer,
    throttleAdapterEnhancer,
    Cache,
} from 'axios-extensions';


var defaultCache = new Cache();

var service = axios.create({
adapter: throttleAdapterEnhancer(cacheAdapterEnhancer(axios.defaults.adapter, { defaultCache: defaultCache }))
});

service.get(`/mypath`, requestOptions)
                .then(function(res) {
//On second request the cached response is returned
                    resolve(res.data);
                }, reject);
```

I've tried 
```js
{cache:false} //Doesn't work
 {cache:new Cache()} //Doesn't work
{forceUpdate:true} //Doesn't work
```

**Comment by kuitos** [comment]
The reason is that you combined throttleAdapterEnhancer and cacheAdapterEnhancer and set throttleAdapterEnhancer as the first enhancer who will take effect firstly.

IMO the behavior was expected, as in a in a short period of time(threshold set with throttleAdapterEnhancer and the default is 1000ms ) we should not make any duplicated request, if you wanna make a fresh one, after the threshold time it would be.
