### ISSUE TITLE
Warning from deprecated / renamed method in LRUCache

### ISSUE THREAD

**Issue by simeonmalchev** [kuitos/axios-extensions#91]
Hi Kuitos,

Appears that there is a deprecated / renamed method in LRUCache, I'm getting this warning with axios-extensions 3.1.4 :

```
index.js:87 The del method is deprecated. Please use cache.delete() instead. DeprecationWarning LRU_CACHE_METHOD_del ƒ del() {
    deprecatedMethod("del", "delete");
    return this.delete;
  }
emitWarning @ index.js:87
warn @ index.js:95
deprecatedMethod @ index.js:70
get del @ index.js:906
isCacheLike @ isCacheLike.ts:8
(anonymous) @ cacheAdapterEnhancer.ts:46
dispatchRequest @ dispatchRequest.js:58
request @ Axios.js:109
Axios.<computed> @ Axios.js:131
wrap @ bind.js:9
get @ AxiosCache.js:15
```

My axios version is 0.27.2 .

**Comment by kuitos** [comment]
Have you ever passed a custom cache to adapter like:
```js
const customCache = new LRUCache();
http.get('/users', { cache: customCache });
```

**Comment by simeonmalchev** [comment]
This is what have:
```
import axios from 'axios';
import { cacheAdapterEnhancer } from 'axios-extensions';
import LRUCache from 'lru-cache';

class SomeClass {
    constructor() {
        this.cache = new LRUCache({ max: 200, ttl: 2 * 60 * 1000 });
        this.axiosCache = axios.create({
            adapter: cacheAdapterEnhancer(axios.defaults.adapter, { enabledByDefault: false }),
            responseType: 'json'
        });
    }

    get = async (url) => {
        return this.axiosCache.get(url, { cache: this.cache });
    };
```

**Comment by simeonmalchev** [comment]
Isn't the problem coming from `isCacheLike.ts` where should be used `cache.delete` instead of `cache.del`?

**Comment by kuitos** [comment]
The problem is you created a custom cache with lru-cache v7, who had deprecated the del method https://github.com/isaacs/node-lru-cache/blob/main/CHANGELOG.md#v7---2022-02

You might need to specified the del method to fix this warning:
```js
const lruCache = new LRUCache({ max: 200, ttl: 2 * 60 * 1000 });
this.cache = {
  get: (...args) => lruCache.get(...args),
  set: (...args) => lruCache.get(...args),
  del: (...args) => lruCache.delete(...args)
}
```

**Comment by simeonmalchev** [comment]
I haven't specified the lru-cache version. The dependency to version v7 is coming from the axios-extension package.json:
```
"dependencies": {
    "lru-cache": "^7.14.0",
    "tslib": "^2.1.0",
    "util": "^0.12.3"
  },
```
Shouldn't this specification of the `del` method that you showed above be part of the axios-extension 3.1.4 code instead of the the user code (my code)?

See how in axios-extension 3.1.3 (your previous version) you're depending on "lru-cache": "^5.1.1" where it seems the del method is not renamed. Now when in 3.1.4 you updated the lru-cache dependency to a new major lru-cache version, isn't it better this spec of the `del` method to be part of the axios-extension code?

**Comment by kuitos** [comment]
There are two points should be clarified:
1. You should not depend on a [phantom dependency](https://stackoverflow.com/questions/56837043/what-are-phantomchildren-in-package-json) in your project, if you wanna use a npm package in your source code, you should declare it in your package.json.
2. axios-extensions defined an interface of custom cache that we must implement the three methods `get` `set` and `del`, not matter what it actually be, either a lru cache or a fifo cache or something else.
![image](https://user-images.githubusercontent.com/5206843/193984182-f4a74c44-c378-4bda-b529-a02c3fcac47b.png)
You passed a del implementation which will trigger a warning while it invoking, that was the problem here.

But I found that we exposed a Cache constructor, which not compatible with lru cache v7 yet.
https://github.com/kuitos/axios-extensions/blob/6ee7b2767e4864f6b9e421ccac01876b51c26515/src/index.ts#L14

I will fix it soon, thanks for your issue report.

**Comment by simeonmalchev** [comment]
No worries, feel free to close this issue whenever you decide.
